package zio.nats.service

import io.nats.service.{Service => JService}
import zio._
import zio.nats.NatsError

// ---------------------------------------------------------------------------
// NatsService trait — public handle for a running service
// ---------------------------------------------------------------------------

/**
 * A running NATS microservice.
 *
 * Obtained via [[zio.nats.Nats.service]]. The service is automatically stopped
 * (with drain) when the enclosing [[Scope]] ends.
 *
 * Provides access to the service's identity, health, and statistics — the same
 * information that remote clients can query via [[ServiceDiscovery]].
 *
 * ==Example==
 * {{{
 * ZIO.scoped {
 *   for {
 *     svc <- nats.service(ServiceConfig("calc", "1.0.0"), bound)
 *     _   <- Console.printLine(s"Service ${svc.name} started [${svc.id}]")
 *     _   <- ZIO.never
 *   } yield ()
 * }
 * }}}
 */
trait NatsService {

  /**
   * Unique instance ID (generated by jnats; stable for the lifetime of this
   * service).
   */
  def id: String

  /** Service name as provided in [[ServiceConfig]]. */
  def name: String

  /** Service version as provided in [[ServiceConfig]]. */
  def version: String

  /** Service description, if provided. */
  def description: Option[String]

  /**
   * This service's ping response (name, version, id, metadata).
   *
   * Never fails: the value is pre-computed by jnats.
   */
  def ping: UIO[PingResponse]

  /**
   * This service's info response (ping + description + endpoint list).
   *
   * Never fails: the value is pre-computed by jnats.
   */
  def info: UIO[InfoResponse]

  /**
   * This service's current statistics.
   *
   * Includes per-endpoint request counts, error counts, and processing times.
   */
  def stats: IO[NatsError, StatsResponse]

  /**
   * Get statistics for a specific endpoint by name.
   *
   * Returns [[None]] if no endpoint with that name is registered.
   */
  def endpointStats(endpointName: String): IO[NatsError, Option[EndpointStats]]

  /** Reset all endpoint statistics counters to zero. */
  def reset: IO[NatsError, Unit]
}

// ---------------------------------------------------------------------------
// NatsServiceLive — private implementation
// ---------------------------------------------------------------------------

private[nats] final class NatsServiceLive(jService: JService) extends NatsService {

  def id: String = jService.getId

  def name: String = jService.getName

  def version: String = jService.getVersion

  def description: Option[String] =
    Option(jService.getInfoResponse.getDescription).filter(_.nonEmpty)

  def ping: UIO[PingResponse] =
    ZIO.succeed(PingResponse.fromJava(jService.getPingResponse))

  def info: UIO[InfoResponse] =
    ZIO.succeed(InfoResponse.fromJava(jService.getInfoResponse))

  def stats: IO[NatsError, StatsResponse] =
    ZIO
      .attempt(StatsResponse.fromJava(jService.getStatsResponse))
      .mapError(NatsError.fromThrowable)

  def endpointStats(endpointName: String): IO[NatsError, Option[EndpointStats]] =
    ZIO
      .attempt(
        StatsResponse
          .fromJava(jService.getStatsResponse)
          .endpoints
          .find(_.name == endpointName)
      )
      .mapError(NatsError.fromThrowable)

  def reset: IO[NatsError, Unit] =
    ZIO.attempt(jService.reset()).mapError(NatsError.fromThrowable)
}
